export type ListingContext = 'housing' | 'automotive';
export type ListingBadge = 'Featured' | 'For Sale' | 'For Rent';
export type HousingType = 'Apartment' | 'Bungalow' | 'Office' | 'Villa' | 'Townhouse';
export type AutomotiveType = 'SUV' | 'Sedan' | 'Hatchback' | 'Commercial' | 'Motorcycle';
export type ListingType = HousingType | AutomotiveType;

export interface ListingAgent {
  name: string;
  avatar: string;
  role: string;
  phone: string;
  email: string;
}

interface BaseListing {
  id: string;
  context: ListingContext;
  title: string;
  type: ListingType;
  location: string;
  price: string;
  priceValue: number;
  image: string;
  badge: ListingBadge;
  featured: boolean;
  description: string;
  agent: ListingAgent;
}

export interface HousingListing extends BaseListing {
  context: 'housing';
  type: HousingType;
  purpose: 'buy' | 'rent' | 'sell';
  beds: number;
  baths: number;
  sqft: number;
}

export interface AutomotiveListing extends BaseListing {
  context: 'automotive';
  type: AutomotiveType;
  purpose: 'buy';
  year: number;
  mileage: number;
  fuel: 'Benzin' | 'Dizel' | 'Hibrit' | 'Elektrik';
  transmission: 'Manuel' | 'Otomatik';
  bodyStyle: string;
}

export type Listing = HousingListing | AutomotiveListing;
export type Property = Listing;

export interface Agent {
  id: string;
  context: ListingContext;
  name: string;
  role: string;
  image: string;
  phone: string;
  email: string;
}

export interface Testimonial {
  id: string;
  name: string;
  role: string;
  image: string;
  quote: string;
  rating: number;
}

export interface City {
  id: string;
  context: ListingContext;
  name: string;
  image: string;
  propertiesCount: number;
}

export const housingPropertyTypes: readonly HousingType[] = [
  'Apartment',
  'Bungalow',
  'Office',
  'Villa',
  'Townhouse',
];

export const automotivePropertyTypes: readonly AutomotiveType[] = [
  'SUV',
  'Sedan',
  'Hatchback',
  'Commercial',
  'Motorcycle',
];

export const propertyTypes = housingPropertyTypes;

export const isHousingListing = (listing: Listing): listing is HousingListing => listing.context === 'housing';
export const isAutomotiveListing = (listing: Listing): listing is AutomotiveListing =>
  listing.context === 'automotive';

export const getListingTypeTurkish = (type: ListingType) => {
  switch (type) {
    case 'Apartment':
      return 'Daire';
    case 'Bungalow':
      return 'Bungalov';
    case 'Office':
      return 'Ofis';
    case 'Villa':
      return 'Villa';
    case 'Townhouse':
      return 'Müstakil Ev';
    case 'SUV':
      return 'SUV';
    case 'Sedan':
      return 'Sedan';
    case 'Hatchback':
      return 'Hatchback';
    case 'Commercial':
      return 'Ticari';
    case 'Motorcycle':
      return 'Motosiklet';
    default:
      return type;
  }
};

export const getPropertyTypeTurkish = getListingTypeTurkish;

export const getBadgeTurkish = (badge: ListingBadge) => {
  switch (badge) {
    case 'Featured':
      return 'Öne Çıkan';
    case 'For Sale':
      return 'Satılık';
    case 'For Rent':
      return 'Kiralık';
    default:
      return badge;
  }
};

const housingAgents: ListingAgent[] = [
  {
    name: 'Canan Yılmaz',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=100&q=80',
    role: 'Lüks Konut Danışmanı',
    phone: '+90 532 123 4567',
    email: 'canan@teknokta.com',
  },
  {
    name: 'Burak Demir',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=100&q=80',
    role: 'Villa ve Rezidans Uzmanı',
    phone: '+90 532 555 4433',
    email: 'burak@teknokta.com',
  },
  {
    name: 'Selin Aktaş',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80',
    role: 'Kiralık Portföy Uzmanı',
    phone: '+90 505 111 2233',
    email: 'selin@teknokta.com',
  },
];

const automotiveAgents: ListingAgent[] = [
  {
    name: 'Emre Aydın',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80',
    role: 'Premium Araç Danışmanı',
    phone: '+90 530 456 8899',
    email: 'emre@teknokta.com',
  },
  {
    name: 'Ece Karaca',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
    role: 'İkinci El Uzmanı',
    phone: '+90 531 223 7788',
    email: 'ece@teknokta.com',
  },
  {
    name: 'Mert Sağlam',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=100&q=80',
    role: 'Ticari Araç Danışmanı',
    phone: '+90 544 998 1100',
    email: 'mert@teknokta.com',
  },
];

const housingListings: HousingListing[] = [
  {
    id: 'housing-1',
    context: 'housing',
    title: 'Boğaz Manzaralı Lüks Villa',
    type: 'Villa',
    location: 'İstanbul',
    price: '32.500.000 TL',
    priceValue: 32500000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    beds: 5,
    baths: 4,
    sqft: 420,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
    description:
      'Geniş bahçe, panoramik manzara ve premium iç mekan detayları ile öne çıkan seçili bir konut portföyü.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-2',
    context: 'housing',
    title: 'Modern Beton ve Cam Villa',
    type: 'Villa',
    location: 'Bodrum',
    price: '28.000.000 TL',
    priceValue: 28000000,
    badge: 'For Sale',
    featured: true,
    purpose: 'buy',
    beds: 4,
    baths: 5,
    sqft: 480,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    description: 'Denize yakın, yüksek tavanlı ve açık plan yaşam alanı sunan modern bir villa.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-3',
    context: 'housing',
    title: 'Şehir Merkezinde Kiralık Penthouse',
    type: 'Apartment',
    location: 'Ankara',
    price: '55.000 TL / ay',
    priceValue: 55000,
    badge: 'For Rent',
    featured: true,
    purpose: 'rent',
    beds: 3,
    baths: 2,
    sqft: 210,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
    description: 'Kısa sürede taşınmaya hazır, ferah planlı ve şehir görünümlü bir penthouse.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-4',
    context: 'housing',
    title: 'Bahçeli Müstakil Aile Evi',
    type: 'Townhouse',
    location: 'Antalya',
    price: '11.900.000 TL',
    priceValue: 11900000,
    badge: 'For Sale',
    featured: false,
    purpose: 'sell',
    beds: 4,
    baths: 3,
    sqft: 235,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    description: 'Sessiz bir bölgede, aile yaşamına uygun bahçeli ve aydınlık bir müstakil ev.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-5',
    context: 'housing',
    title: 'Plaza İçi Hazır Ofis Katı',
    type: 'Office',
    location: 'İstanbul',
    price: '95.000 TL / ay',
    priceValue: 95000,
    badge: 'For Rent',
    featured: false,
    purpose: 'rent',
    beds: 0,
    baths: 2,
    sqft: 320,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    description: 'Kurumsal ekipler için merkezi konumda, toplantı odalı ve hazır kullanıma uygun ofis.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-6',
    context: 'housing',
    title: 'Havuzlu Bungalov Yaşam Alanı',
    type: 'Bungalow',
    location: 'Antalya',
    price: '8.400.000 TL',
    priceValue: 8400000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 2,
    baths: 2,
    sqft: 150,
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    description: 'Doğa yakın, butik yaşam isteyenler için tasarlanmış sakin ve özel bir portföy.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-7',
    context: 'housing',
    title: 'İzmir Kordon Boyu Kiralık 3+1 Daire',
    type: 'Apartment',
    location: 'İzmir',
    price: '48.000 TL / ay',
    priceValue: 48000,
    badge: 'For Rent',
    featured: true,
    purpose: 'rent',
    beds: 3,
    baths: 2,
    sqft: 180,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    description: 'Kordon manzaralı, geniş balkonlu, ankastre setli ve ebeveyn banyolu lüks daire.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-8',
    context: 'housing',
    title: 'Antalya Lara Sahilinde Lüks Villa',
    type: 'Villa',
    location: 'Antalya',
    price: '42.000.000 TL',
    priceValue: 42000000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    beds: 6,
    baths: 5,
    sqft: 520,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    description: 'Denize sıfır, özel yüzme havuzlu, akıllı ev otomasyonlu ve jakuzili ultra lüks villa.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-9',
    context: 'housing',
    title: 'Bodrum Yalıkavak Marina Manzaralı Villa',
    type: 'Villa',
    location: 'Bodrum',
    price: '58.000.000 TL',
    priceValue: 58000000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    beds: 5,
    baths: 6,
    sqft: 460,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    description: 'Yalıkavak Marina manzaralı, sonsuzluk havuzlu, müştemilatlı ve geniş peyzajlı özel malikane.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-10',
    context: 'housing',
    title: 'Bursa Nilüfer Satılık Modern Daire',
    type: 'Apartment',
    location: 'Bursa',
    price: '6.900.000 TL',
    priceValue: 6900000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 3,
    baths: 2,
    sqft: 165,
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
    description: 'Nilüfer merkezde, site içerisinde, kapalı otoparklı, çocuk oyun alanlı konforlu aile dairesi.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-11',
    context: 'housing',
    title: 'Muğla Fethiye Orman İçi Taş Ev',
    type: 'Townhouse',
    location: 'Muğla',
    price: '14.500.000 TL',
    priceValue: 14500000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 3,
    baths: 2,
    sqft: 190,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
    description: 'Doğa ile iç içe, ahşap ve taş mimarili, özel havuzlu ve şömineli müstakil yaşam alanı.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-12',
    context: 'housing',
    title: 'İstanbul Kadıköy Kiralık Stüdyo Daire',
    type: 'Apartment',
    location: 'İstanbul',
    price: '32.000 TL / ay',
    priceValue: 32000,
    badge: 'For Rent',
    featured: false,
    purpose: 'rent',
    beds: 1,
    baths: 1,
    sqft: 65,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    description: 'Moda sahiline yürüme mesafesinde, tamamen eşyalı, modern tasarımlı 1+1 stüdyo daire.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-13',
    context: 'housing',
    title: 'Ankara Çankaya Satılık Tripleks Ev',
    type: 'Townhouse',
    location: 'Ankara',
    price: '18.900.000 TL',
    priceValue: 18900000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 5,
    baths: 3,
    sqft: 350,
    image: 'https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?auto=format&fit=crop&w=800&q=80',
    description: 'Çankaya\'da elit sitede, özel bahçeli, kapalı garajlı ve saunalı lüks tripleks villa/townhouse.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-14',
    context: 'housing',
    title: 'Sapanca Gölü Kıyısında Lüks Bungalov',
    type: 'Bungalow',
    location: 'Yalova',
    price: '9.200.000 TL',
    priceValue: 9200000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    beds: 2,
    baths: 1,
    sqft: 110,
    image: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=800&q=80',
    description: 'Göl manzaralı, verandalı, açık havuzlu ve şömineli huzurlu ahşap bungalov.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-15',
    context: 'housing',
    title: 'Şişli Bomonti Rezidans Ofisi',
    type: 'Office',
    location: 'İstanbul',
    price: '110.000 TL / ay',
    priceValue: 110000,
    badge: 'For Rent',
    featured: true,
    purpose: 'rent',
    beds: 0,
    baths: 2,
    sqft: 220,
    image: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    description: 'Bomonti merkezinde, yüksek katlı, şehir manzaralı ve sekretaryalı modern plaza ofisi.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-16',
    context: 'housing',
    title: 'Bodrum Ortakent Kiralık Yazlık Ev',
    type: 'Townhouse',
    location: 'Bodrum',
    price: '75.000 TL / ay',
    priceValue: 75000,
    badge: 'For Rent',
    featured: false,
    purpose: 'rent',
    beds: 3,
    baths: 2,
    sqft: 140,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80',
    description: 'Ortakent yahşi plajına yürüme mesafesinde, ortak havuzlu site içerisinde yazlık dubleks.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-17',
    context: 'housing',
    title: 'İzmir Çeşme Alaçatı Satılık Taş Villa',
    type: 'Villa',
    location: 'İzmir',
    price: '29.500.000 TL',
    priceValue: 29500000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    beds: 4,
    baths: 3,
    sqft: 210,
    image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80',
    description: 'Alaçatı merkezde, taş mimarili, özel havuzlu ve cumbalı lüks villa portföyü.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-18',
    context: 'housing',
    title: 'Antalya Konyaaltı Denize Yakın 2+1',
    type: 'Apartment',
    location: 'Antalya',
    price: '5.200.000 TL',
    priceValue: 5200000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 2,
    baths: 1,
    sqft: 105,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    description: 'Konyaaltı plajlarına 500m mesafede, havuzlu lüks blokta satılık modern daire.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-19',
    context: 'housing',
    title: 'Ankara Ümitköy Satılık Havuzlu Villa',
    type: 'Villa',
    location: 'Ankara',
    price: '24.500.000 TL',
    priceValue: 24500000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 5,
    baths: 4,
    sqft: 380,
    image: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80',
    description: 'Ümitköy\'ün en köklü sitesinde müstakil havuzlu, bakımlı ve geniş bahçeli tripleks villa.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-20',
    context: 'housing',
    title: 'İstanbul Beşiktaş Kiralık Eşyalı Daire',
    type: 'Apartment',
    location: 'İstanbul',
    price: '60.000 TL / ay',
    priceValue: 60000,
    badge: 'For Rent',
    featured: false,
    purpose: 'rent',
    beds: 2,
    baths: 1,
    sqft: 90,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
    description: 'Beşiktaş merkezde, çarşıya ve sahile 2 dakika mesafede, lüks mobilyalı temiz daire.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-21',
    context: 'housing',
    title: 'İzmir Karşıyaka Deniz Manzaralı 4+1',
    type: 'Apartment',
    location: 'İzmir',
    price: '19.800.000 TL',
    priceValue: 19800000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    beds: 4,
    baths: 2,
    sqft: 220,
    image: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=800&q=80',
    description: 'Karşıyaka yalı caddesinde, kesintisiz deniz manzaralı, geniş salonlu ve prestijli daire.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-22',
    context: 'housing',
    title: 'Bursa Osmangazi Kiralık Ticari Ofis',
    type: 'Office',
    location: 'Bursa',
    price: '45.000 TL / ay',
    priceValue: 45000,
    badge: 'For Rent',
    featured: false,
    purpose: 'rent',
    beds: 0,
    baths: 1,
    sqft: 110,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    description: 'Metro istasyonuna yakın, tabela değeri yüksek, avukatlık veya mali müşavirliğe uygun ofis.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-23',
    context: 'housing',
    title: 'Trabzon Akçaabat Deniz Manzaralı Konut',
    type: 'Apartment',
    location: 'Muğla',
    price: '7.800.000 TL',
    priceValue: 7800000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 3,
    baths: 2,
    sqft: 160,
    image: 'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=800&q=80',
    description: 'Akçaabat sahil yoluna hakim konumda, doğa ve deniz manzaralı, ebeveyn banyolu daire.',
    agent: housingAgents[1],
  },
  {
    id: 'housing-24',
    context: 'housing',
    title: 'Bodrum Gümüşlük Kiralık Bungalov Ev',
    type: 'Bungalow',
    location: 'Bodrum',
    price: '65.000 TL / ay',
    priceValue: 65000,
    badge: 'For Rent',
    featured: false,
    purpose: 'rent',
    beds: 1,
    baths: 1,
    sqft: 85,
    image: 'https://images.unsplash.com/photo-1475855581690-80accde3ae2b?auto=format&fit=crop&w=800&q=80',
    description: 'Gümüşlük sırtlarında, günbatımı manzaralı, müstakil bahçeli ve taş havuzlu şirin bungalov.',
    agent: housingAgents[2],
  },
  {
    id: 'housing-25',
    context: 'housing',
    title: 'Ankara İncek Yeni Yapım 3+1 Daire',
    type: 'Apartment',
    location: 'Ankara',
    price: '8.250.000 TL',
    priceValue: 8250000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    beds: 3,
    baths: 2,
    sqft: 145,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    description: 'İncek\'in gelişen bölgesinde, yeni tamamlanmış lüks projede kapalı otoparklı sıfır daire.',
    agent: housingAgents[0],
  },
  {
    id: 'housing-26',
    context: 'housing',
    title: 'Antalya Belek Golf Sahası Yakınında Villa',
    type: 'Villa',
    location: 'Antalya',
    price: '34.000.000 TL',
    priceValue: 34000000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    beds: 4,
    baths: 4,
    sqft: 320,
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Belek golf sahalarına komşu, özel korunaklı bahçe içinde havuzlu ve sauna odalı villa.',
    agent: housingAgents[1],
  }
];

const automotiveListings: AutomotiveListing[] = [
  {
    id: 'auto-1',
    context: 'automotive',
    title: '2023 BMW X5 xDrive40d M Sport',
    type: 'SUV',
    location: 'İstanbul',
    price: '6.850.000 TL',
    priceValue: 6850000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2023,
    mileage: 18500,
    fuel: 'Dizel',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80',
    description: 'Düşük kilometreli, yetkili servis bakımlı ve premium sürüş paketli temiz bir SUV.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-2',
    context: 'automotive',
    title: '2024 Mercedes C 200 AMG',
    type: 'Sedan',
    location: 'Ankara',
    price: '4.290.000 TL',
    priceValue: 4290000,
    badge: 'For Sale',
    featured: true,
    purpose: 'buy',
    year: 2024,
    mileage: 9200,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Sedan',
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80',
    description: 'Yeni kasa, cam tavanlı ve premium iç trimli dikkat çekici bir sedan seçeneği.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-3',
    context: 'automotive',
    title: '2022 Volkswagen Golf 1.5 eTSI',
    type: 'Hatchback',
    location: 'İzmir',
    price: '1.680.000 TL',
    priceValue: 1680000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2022,
    mileage: 36000,
    fuel: 'Hibrit',
    transmission: 'Otomatik',
    bodyStyle: 'Hatchback',
    image: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=800&q=80',
    description: 'Şehir içi kullanım için ekonomik, güvenlik paketleri tam ve temiz kullanılmış bir hatchback.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-4',
    context: 'automotive',
    title: '2021 Ford Transit Custom 320L',
    type: 'Commercial',
    location: 'Bursa',
    price: '1.395.000 TL',
    priceValue: 1395000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2021,
    mileage: 89000,
    fuel: 'Dizel',
    transmission: 'Manuel',
    bodyStyle: 'Panel Van',
    image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=800&q=80',
    description: 'Filo çıkışlı, ekspertiz raporlu ve ticari kullanım için hazır bir transit.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-5',
    context: 'automotive',
    title: '2024 Tesla Model Y Long Range',
    type: 'SUV',
    location: 'Antalya',
    price: '3.950.000 TL',
    priceValue: 3950000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2024,
    mileage: 7400,
    fuel: 'Elektrik',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80',
    description: 'Uzun menzil batarya, gelişmiş sürüş destekleri ve temiz boya durumu ile öne çıkan EV.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-6',
    context: 'automotive',
    title: '2020 Yamaha TMAX Tech Max',
    type: 'Motorcycle',
    location: 'Muğla',
    price: '890.000 TL',
    priceValue: 890000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2020,
    mileage: 21000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Maxi Scooter',
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
    description: 'Bakımları tam, şehir içi ve uzun yol kullanımına uygun premium maxi scooter.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-7',
    context: 'automotive',
    title: '2022 Porsche Taycan GTS',
    type: 'Sedan',
    location: 'İstanbul',
    price: '8.400.000 TL',
    priceValue: 8400000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2022,
    mileage: 12000,
    fuel: 'Elektrik',
    transmission: 'Otomatik',
    bodyStyle: 'Sport Sedan',
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80',
    description: 'Doğuş çıkışlı, hatasız boyasız, özel renk ve karbon iç detaylara sahip elektrikli spor sedan.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-8',
    context: 'automotive',
    title: '2023 Audi A4 40 TDI Quattro S Line',
    type: 'Sedan',
    location: 'Ankara',
    price: '2.950.000 TL',
    priceValue: 2950000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2023,
    mileage: 24000,
    fuel: 'Dizel',
    transmission: 'Otomatik',
    bodyStyle: 'Sedan',
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80',
    description: 'Hatasız, yetkili servis bakımlı, matrix led farlı ve hayalet ekranlı premium sedan.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-9',
    context: 'automotive',
    title: '2021 Land Rover Defender 110 D250',
    type: 'SUV',
    location: 'Bodrum',
    price: '7.200.000 TL',
    priceValue: 7200000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2021,
    mileage: 42000,
    fuel: 'Dizel',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80',
    description: 'Hatasız, boyasız, geniş aksesuarlı ve arazi paketli mükemmel durumda lüks SUV.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-10',
    context: 'automotive',
    title: '2020 Honda Civic 1.5 VTEC Sport Plus',
    type: 'Sedan',
    location: 'İzmir',
    price: '1.250.000 TL',
    priceValue: 1250000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2020,
    mileage: 55000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Sedan',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    description: 'Yetkili servis bakımlı, cam tavanlı, geri görüş kameralı ve temiz kullanılmış aile aracı.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-11',
    context: 'automotive',
    title: '2023 Peugeot 3008 1.5 BlueHDi GT',
    type: 'SUV',
    location: 'Bursa',
    price: '1.980.000 TL',
    priceValue: 1980000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2023,
    mileage: 15000,
    fuel: 'Dizel',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    description: 'GT paket, otonom sürüş, masajlı koltuklar ve panoramik cam tavan özellikli şık SUV.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-12',
    context: 'automotive',
    title: '2019 Fiat Doblo Cargo 1.3 Multijet',
    type: 'Commercial',
    location: 'İstanbul',
    price: '620.000 TL',
    priceValue: 620000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2019,
    mileage: 112000,
    fuel: 'Dizel',
    transmission: 'Manuel',
    bodyStyle: 'Panel Van',
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=800&q=80',
    description: 'İlk sahibinden, faturalı, bakımları zamanında yapılmış ekonomik ticari araç.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-13',
    context: 'automotive',
    title: '2023 Honda Forza 250',
    type: 'Motorcycle',
    location: 'Antalya',
    price: '285.000 TL',
    priceValue: 285000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2023,
    mileage: 4500,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Maxi Scooter',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
    description: 'Aksesuarlı, çanta demirli ve kazasız tertemiz şehir içi yol arkadaşı.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-14',
    context: 'automotive',
    title: '2022 Hyundai i20 1.4 MPI Elite',
    type: 'Hatchback',
    location: 'Ankara',
    price: '980.000 TL',
    priceValue: 980000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2022,
    mileage: 28000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Hatchback',
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80',
    description: 'Bayan sahibinden, değişensiz, Elite en dolu paket, sıfır ayarında hatchback.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-15',
    context: 'automotive',
    title: '2024 Volvo XC90 B5 AWD Ultimate',
    type: 'SUV',
    location: 'İstanbul',
    price: '9.850.000 TL',
    priceValue: 9850000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2024,
    mileage: 3500,
    fuel: 'Hibrit',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    description: 'Yeni nesil hafif hibrit motor, 7 koltuklu, bowers & wilkins ses sistemli, hatasız lüks SUV.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-16',
    context: 'automotive',
    title: '2021 Renault Clio 1.0 TCe Touch',
    type: 'Hatchback',
    location: 'İzmir',
    price: '870.000 TL',
    priceValue: 870000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2021,
    mileage: 48000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Hatchback',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80',
    description: 'Ekonomik sürüş, yedek anahtarı mevcut, bakımı yeni yapılmış temiz Clio.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-17',
    context: 'automotive',
    title: '2022 Mercedes GLC 300d 4MATIC AMG',
    type: 'SUV',
    location: 'Antalya',
    price: '5.900.000 TL',
    priceValue: 5900000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2022,
    mileage: 22000,
    fuel: 'Dizel',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80',
    description: 'AMG paket, premium donanımlı, boyasız çiziksiz mükemmel durumda lüks SUV.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-18',
    context: 'automotive',
    title: '2023 Cupra Formentor 1.5 TSI VZ',
    type: 'SUV',
    location: 'Bursa',
    price: '2.150.000 TL',
    priceValue: 2150000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2023,
    mileage: 11000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80',
    description: 'Mat füme renk, bucket koltuklar, beats ses sistemi ve hatasız sıfır kokulu Cupra.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-19',
    context: 'automotive',
    title: '2022 Toyota Corolla 1.5 Dream Multidrive S',
    type: 'Sedan',
    location: 'Ankara',
    price: '1.180.000 TL',
    priceValue: 1180000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2022,
    mileage: 32000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Sedan',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80',
    description: 'İlk sahibinden, kazasız boyasız, servis bakımlı ve garantisi devam eden aile sedanı.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-20',
    context: 'automotive',
    title: '2024 BMW i4 eDrive40 M Sport',
    type: 'Sedan',
    location: 'İstanbul',
    price: '3.980.000 TL',
    priceValue: 3980000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2024,
    mileage: 4800,
    fuel: 'Elektrik',
    transmission: 'Otomatik',
    bodyStyle: 'Gran Coupe',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
    description: 'M Sport paket, head-up display, lazer farlar ve otonom sürüş asistanlı sıfır ayarında EV.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-21',
    context: 'automotive',
    title: '2021 Volkswagen Caddy 2.0 TDI Style',
    type: 'Commercial',
    location: 'Bursa',
    price: '1.580.000 TL',
    priceValue: 1580000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2021,
    mileage: 64000,
    fuel: 'Dizel',
    transmission: 'Otomatik',
    bodyStyle: 'Kombivan',
    image: 'https://images.unsplash.com/photo-1517524206127-48bbd363f3d7?auto=format&fit=crop&w=800&q=80',
    description: 'En dolu Style paket, cam tavanlı, şerit takip ve kör nokta uyarı sistemli lüks ticari.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-22',
    context: 'automotive',
    title: '2023 Vespa GTS 300 Super Sport',
    type: 'Motorcycle',
    location: 'Muğla',
    price: '385.000 TL',
    priceValue: 385000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2023,
    mileage: 2200,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'Scooter',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=80',
    description: 'Mat siyah renk, hatasız çiziksiz, kapalı garajda muhafaza edilmiş Vespa keyfi.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-23',
    context: 'automotive',
    title: '2020 Fiat Egea 1.3 Multijet Easy',
    type: 'Sedan',
    location: 'Ankara',
    price: '730.000 TL',
    priceValue: 730000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2020,
    mileage: 92000,
    fuel: 'Dizel',
    transmission: 'Manuel',
    bodyStyle: 'Sedan',
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80',
    description: 'Yakıt cimrisi, ağır bakımları tamamlanmış, masrafsız temiz kullanılmış aile otomobili.',
    agent: automotiveAgents[1],
  },
  {
    id: 'auto-24',
    context: 'automotive',
    title: '2022 Dacia Duster 1.3 TCe Prestige Plus',
    type: 'SUV',
    location: 'Antalya',
    price: '1.240.000 TL',
    priceValue: 1240000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2022,
    mileage: 38000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    description: 'Prestige Plus en dolu paket, 360 derece kamera, kör nokta uyarı ve hatasız kondisyon.',
    agent: automotiveAgents[2],
  },
  {
    id: 'auto-25',
    context: 'automotive',
    title: '2023 Audi Q3 35 TFSI Advanced',
    type: 'SUV',
    location: 'İstanbul',
    price: '3.150.000 TL',
    priceValue: 3150000,
    badge: 'Featured',
    featured: true,
    purpose: 'buy',
    year: 2023,
    mileage: 14000,
    fuel: 'Benzin',
    transmission: 'Otomatik',
    bodyStyle: 'SUV',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    description: 'Panoramik cam tavan, sanal kokpit, elektrikli bagaj ve şerit terk uyarı sistemli sıfır ayarında.',
    agent: automotiveAgents[0],
  },
  {
    id: 'auto-26',
    context: 'automotive',
    title: '2022 Mercedes Vito Tourer 119 CDI Select',
    type: 'Commercial',
    location: 'Trabzon',
    price: '2.650.000 TL',
    priceValue: 2650000,
    badge: 'For Sale',
    featured: false,
    purpose: 'buy',
    year: 2022,
    mileage: 49000,
    fuel: 'Dizel',
    transmission: 'Otomatik',
    bodyStyle: 'Minibüs',
    image: 'https://images.unsplash.com/photo-1517524206127-48bbd363f3d7?auto=format&fit=crop&w=800&q=80',
    description: '9 kişilik, ultra lüks VIP dizayn, çift klimalı, buzdolaplı ve yolcu televizyonlu Vito.',
    agent: automotiveAgents[1],
  }
];

export const mockListings: Listing[] = [...housingListings, ...automotiveListings];
export const mockProperties: Property[] = mockListings;

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    context: 'housing',
    name: 'Canan Yılmaz',
    role: 'Lüks Konut Danışmanı',
    image: housingAgents[0].avatar,
    phone: housingAgents[0].phone,
    email: housingAgents[0].email,
  },
  {
    id: 'agent-2',
    context: 'housing',
    name: 'Burak Demir',
    role: 'Villa ve Rezidans Uzmanı',
    image: housingAgents[1].avatar,
    phone: housingAgents[1].phone,
    email: housingAgents[1].email,
  },
  {
    id: 'agent-3',
    context: 'housing',
    name: 'Selin Aktaş',
    role: 'Kiralık Portföy Uzmanı',
    image: housingAgents[2].avatar,
    phone: housingAgents[2].phone,
    email: housingAgents[2].email,
  },
  {
    id: 'agent-4',
    context: 'automotive',
    name: 'Emre Aydın',
    role: 'Premium Araç Danışmanı',
    image: automotiveAgents[0].avatar,
    phone: automotiveAgents[0].phone,
    email: automotiveAgents[0].email,
  },
  {
    id: 'agent-5',
    context: 'automotive',
    name: 'Ece Karaca',
    role: 'İkinci El Uzmanı',
    image: automotiveAgents[1].avatar,
    phone: automotiveAgents[1].phone,
    email: automotiveAgents[1].email,
  },
  {
    id: 'agent-6',
    context: 'automotive',
    name: 'Mert Sağlam',
    role: 'Ticari Araç Danışmanı',
    image: automotiveAgents[2].avatar,
    phone: automotiveAgents[2].phone,
    email: automotiveAgents[2].email,
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Ahmet Yılmaz',
    role: 'Konut Alıcısı',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    quote:
      'Tek Nokta ile yeni evimizi bulma süreci beklediğimizden daha hızlı ve güvenli ilerledi.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Sibel Çelik',
    role: 'Araç Alıcısı',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    quote:
      'Ekspertiz, fiyat doğrulaması ve iletişim tarafında bize ciddi zaman kazandıran temiz bir deneyim oldu.',
    rating: 5,
  },
];

export const mockCities: City[] = [
  {
    id: 'city-1',
    context: 'housing',
    name: 'İstanbul',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 14,
  },
  {
    id: 'city-2',
    context: 'housing',
    name: 'Antalya',
    image: 'https://images.unsplash.com/photo-1506970113724-bc41e3a46d92?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 9,
  },
  {
    id: 'city-3',
    context: 'housing',
    name: 'Bodrum',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 11,
  },
  {
    id: 'city-4',
    context: 'housing',
    name: 'Ankara',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 7,
  },
  {
    id: 'city-5',
    context: 'automotive',
    name: 'İstanbul',
    image: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 21,
  },
  {
    id: 'city-6',
    context: 'automotive',
    name: 'Ankara',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 13,
  },
  {
    id: 'city-7',
    context: 'automotive',
    name: 'İzmir',
    image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 10,
  },
  {
    id: 'city-8',
    context: 'automotive',
    name: 'Bursa',
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=600&q=80',
    propertiesCount: 8,
  },
];
